def sample():
    time.sleep(50)
    time.sleep(30)
    time.sleep(5)
    SendKey(Settings,10,1)
    SendKey(Up,4,1)
    SendKey(Up,4,1)
    SendKey(Ok,10,1)
    SendKey(Down,3,6)
    SendKey(Ok,8,1)
    SendKey(Down,5,19)
    time.sleep(5)
    SendKey(Ok,8,1)
    SendKey(No_1,1,1)
    SendKey(No_1,1,1)
    SendKey(No_1,1,1)
    SendKey(No_1,3,1)
    SendKey(Left,3,1)
    SendKey(Ok,5,1)
    #IF_StartCapture
    #ELSE
    #DELAY_Sec22.0
    #Result_FAIL
    #IF_End
    
    time.sleep(5)
    SendKey(Return,2,1)
    SendKey(Return,2,1)
    SendKey(Return,2,1)
    SendKey(Return,2,1)
    #unknownEnd
